name: instantkhata_distributors
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_icons: ^1.1.0

  bloc: ^4.0.0

  flutter_bloc: ^4.0.0

  fl_chart: ^0.10.0

  flutter_sticky_header: "^0.4.2"

  flutter_speed_dial: ^1.2.5

  get_it: ^4.0.2

  equatable: ^1.2.0

  dartz: ^0.9.1

  translator: ^0.1.5

  shimmer: ^1.1.1

  connectivity: ^0.4.3+7

  http: ^0.12.1

  shared_preferences: ^0.5.7+3

  cupertino_icons: ^0.1.3

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile.png

  fonts:
    - family: Axiforma
      fonts:
        - asset: fonts/Axiforma-Book.ttf
        - asset: fonts/Axiforma-Black.ttf
        - asset: fonts/Axiforma-BlackItalic.ttf
        - asset: fonts/Axiforma-Bold.ttf
        - asset: fonts/Axiforma-BoldItalic.ttf
        - asset: fonts/Axiforma-ExtraBold.ttf
        - asset: fonts/Axiforma-ExtraBoldItalic.ttf
        - asset: fonts/Axiforma-Heavy.ttf
        - asset: fonts/Axiforma-HeavyItalic.ttf
        - asset: fonts/Axiforma-Light.ttf
        - asset: fonts/Axiforma-LightItalic.ttf
        - asset: fonts/Axiforma-BookItalic.ttf
        - asset: fonts/Axiforma-Thin.ttf
        - asset: fonts/Axiforma-ThinItalic.ttf
        - asset: fonts/Axiforma-Regular.ttf
        - asset: fonts/Axiforma-SemiBold.ttf
        - asset: fonts/Axiforma-Italic.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf